### ISSUE TITLE
install.sh improvements txt based

### ISSUE THREAD

**Issue by manfredmuth** [sa-mw-dach/bobbycar#49]
Hi Ortwin.
See my comments marked with @Ortwin.
* missing helm can be solved in the install.sh #50 
* the weather API needs a NULL value as default

---
# Preparation tasks

## Prepare your bastion environment:

You can use the **install.sh** script to simply install the demo.

Upfront running the install.sh script you need on your bastion host:

What you will need is:
* oc client
* helm installed
* a local copy of the GIT repo
* Gather information for **install.sh**

### oc client installation

Please follow the latest documentation to have an **oc client** available on your bastion host: https://docs.openshift.com/container-platform/4.8/cli_reference/openshift_cli/getting-started-cli.html 

### HELM installation

@Ortwin: HELM muss da sein, daher koennte man das auch in der install.sh abfangen #50 ...

As we currently rely on HELM charts for the deployment of our environment, please make sure to have the latest HELM release available on your bastion host by following the below procedure:

```
curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm

chmod 755 /usr/local/bin/helm
```
### A local GIT copy

Clone the GIT repo to your bastion host. Feel free to use your preferred method of choice ( ssh/https). In this example https was the easiest way.

```
git clone https://github.com/sa-mw-dach/bobbycar.git
```

### Gather information for **install.sh**

With the GIT clone you have the following scripts available:

```
.
├── cleanup.sh
├── install_cleanup_vars.sh
├── install.sh
└── README.md
```
Please add installation information to **install_cleanup_vars.sh**

@Ortwin: Die Weather API KEY values sollten einen Inhalt haben "" , weil sonst das install.sh fehl schlägt mit einem NIL Fehler
```
NAMESPACE=bobbycar
APP_DOMAIN=<e.g apps.cluster-pnc6l.pnc6l.sandbox52.opentlc.com>
API_DOMAIN=<e.g. api.cluster-pnc6l.pnc6l.sandbox52.opentlc.com>

GOOGLE_API_KEY=<add your information>
OWM_WEATHER_API_KEY=""
IBM_WEATHER_API_KEY=""
```

## Installation

Once you are done - you are ready to start the installation

```./install.sh```

**Comment by ortwinschneider** [comment]
Thanks Manfred for the info!!

I've updated the install instructions.
If there is anything missing, please reopen the issue.
