### ISSUE TITLE
RFE: Use OCS and its object storage

### ISSUE THREAD

**Issue by mykaul** [sa-mw-dach/bobbycar#5]
It'd be cool to use OCS for the storage.

**Comment by DanielFroehlich** [comment]
OCP4 has OCS and S3 APIs ready to use

**Comment by mykaul** [comment]
> OCP4 has OCS and S3 APIs ready to use

It doesn't have it, but OCS 4 can be installed on OCP 4 and indeed has S3 APIs (across clouds) that is ready to be used. Indeed, that's why I'm asking for this (and wondering how it was missed initially, when all other products were integrated into this nice demo...)

**Comment by wrichter** [comment]
„Ocp4“ in this case refers to a specific cluster (the fourth ocp cluster in the stormshift rhv Env). Yes the naming is a bit confusing....
