### ISSUE TITLE
Bobbycar $NAMESPACE is not being created 

### ISSUE THREAD

**Issue by mickume** [sa-mw-dach/bobbycar#51]
The Bobbycar $NAMESPACE is not being created when INSTALL_OPERATORS=false ...

```shell
if [[ "$INSTALL_OPERATORS" == true ]]; then
log "Creating namespace $NAMESPACE for Bobbycar demo"
oc new-project "$NAMESPACE" || true
```

Maybe just moving the `oc new-project` command in front of the block will do ... ignoring the error message if $NAMESPACE already exists ...

**Comment by ortwinschneider** [comment]
Yes, the namespace must have been manually created in advance in order to install the namespaced operators manually....
