### ISSUE TITLE
have the option to replace GoogleMaps with OpenstreetMap or any other map service

### ISSUE THREAD

**Issue by rmandrad** [sa-mw-dach/bobbycar#6]
Hi, first great demo and showcase of redhat tech! 

Would it be possible to replace the google maps with a free opensource solution such as [openstreetmap  ](https://www.openstreetmap.org/#map=5/54.910/-3.432)?

**Comment by ortwinschneider** [comment]
Thank you!
We will definitely have a look into this, as it was also our first intention to use OSM. 
Main reason for the demo to use GMaps was StreetView. Not sure if this works with OSM.
OpenStreetView moved to KartaView.... so we will check this.

**Comment by rmandrad** [comment]
agree that Kartaview will not be there as Google ... I am thinking about dishing out the streetmapview and perhaps use OSM for BobbyPlane I know OSM is used for planetracking elsewhere
